export const API_BASE_URL = ''
export const API_LOGIN = '/auth/jwt/login'
export const API_LOGOUT = '/auth/jwt/logout'
export const API_WAZ_SPREAD = '/api/waz/spread'
export const API_WAZ_CALCULATE_SPREAD = '/api/waz/calculatespread'
export const API_USERS_ME = '/users/me'
